name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm -w run lint
        continue-on-error: true

      - name: Run tests
        run: pnpm -w run test

      - name: Run npm audit
        run: pnpm -w audit --audit-level=moderate || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: services/**/coverage || ./coverage || ''
