name: Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: pnpm install && pnpm -w run build
      - name: Build and push Docker images
        run: echo "Build and push images to registry (configure credentials)"
